### ISSUE TITLE
Sorry,but  the  emulator  seems not work  correct on my pc

### ISSUE THREAD

**Issue by fanelwin** [xrip/gamate#1]
I tried many games, the  emulator can  starts the game with screen and sound, but In most times, the  keys (ENTER \SPACE\Z\X) doesn't  works, only in very very few times ,the keys works, i dont why.
my pc runs  on win10 64bit.

I  really like this  emulator,thank you for your work!

**Comment by xrip** [comment]
I'll invesigate the issue, but on all of my pc's works fine. So arrows works well, but other inputs not?
May be you have switched input langue?

**Comment by fanelwin** [comment]
thank you for your reply,  In most times, all the keys  doesn't work, my default input  is  enlish . Could it run in fullscreen mode?

**Comment by fanelwin** [comment]
sorry,my bad,  it is  the default input problem,thank you very much!
